-- Create databese
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE htbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states (
	id INT UNIQUE NOT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(256) NOT NULL
	);
